name: calentre
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

## Min Dart SDK to be used.
environment:
  sdk: ">=2.18.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.5
  flutter_svg: ^2.0.6
  go_router: ^7.1.1
  flutter_bloc: ^8.1.3
  bloc_test: ^9.1.3
  equatable: ^2.0.5
  feature_notifier: ^1.0.6
  animate_gradient: ^0.0.2+1
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  dio: ^5.3.1
  supabase_flutter: ^1.10.13
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  get_it: ^7.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
